/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#define UTF_8 "UTF-8"

/* Header for class com_yiran_securitykey_NativeUtils */

#ifndef _Included_com_yiran_securitykey_NativeUtils
#define _Included_com_yiran_securitykey_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yiran_securitykey_NativeUtils
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yiran_securitykey_NativeUtils_getKey
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
